import * as React from 'react';
import {Stack, Flex} from '@workday/canvas-kit-labs-react/layout';

const data = [
  {
    name: 'Burundi Buyenzi',
    country: 'Burundi',
    region: 'Africa',
    subRegion: 'Buyenzi',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.55',
    flavorProfile: 'honey & peach',
  },
  {
    name: 'Burundi Bweru',
    country: 'Burundi',
    region: 'Africa',
    subRegion: 'Bweru',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.31',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Ethiopia Harrar',
    country: 'Ethiopia',
    region: 'Africa',
    subRegion: 'Harrar',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$18.89',
    flavorProfile: 'honey & peach',
  },
  {
    name: 'Ethiopia Jimma',
    country: 'Ethiopia',
    region: 'Africa',
    subRegion: 'Jimma',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.27',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Ethiopia Limu',
    country: 'Ethiopia',
    region: 'Africa',
    subRegion: 'Limu',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$15.61',
    flavorProfile: 'blackberry & plum',
  },
  {
    name: 'Ethiopia Sidamo',
    country: 'Ethiopia',
    region: 'Africa',
    subRegion: 'Sidamo',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$15.79',
    flavorProfile: 'sweet & smooth',
  },
  {
    name: 'Ethiopia Yirgacheffe',
    country: 'Ethiopia',
    region: 'Africa',
    subRegion: 'Yirgacheffe',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.97',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Rwanda Akagera',
    country: 'Rwanda',
    region: 'Africa',
    subRegion: 'Akagera',
    roastLevel: 'Dark',
    type: 'Blend',
    bagWeight: 12,
    price: '$22.95',
    flavorProfile: 'rich & comforting',
  },
  {
    name: 'Rwanda Kivu',
    country: 'Rwanda',
    region: 'Africa',
    subRegion: 'Kivu',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.38',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Rwanda Kizi Rift',
    country: 'Rwanda',
    region: 'Africa',
    subRegion: 'Kizi Rift',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.60',
    flavorProfile: 'honey & peach',
  },
  {
    name: 'Rwanda Muhazi',
    country: 'Rwanda',
    region: 'Africa',
    subRegion: 'Muhazi',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$12.88',
    flavorProfile: 'caramel & toffee',
  },
  {
    name: 'Rwanda Virunga',
    country: 'Rwanda',
    region: 'Africa',
    subRegion: 'Virunga',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.21',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Uganda Bugisu',
    country: 'Uganda',
    region: 'Africa',
    subRegion: 'Bugisu',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.50',
    flavorProfile: 'sweet & smooth',
  },
  {
    name: 'Uganda Lira',
    country: 'Uganda',
    region: 'Africa',
    subRegion: 'Lira',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.89',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Uganda Masaka',
    country: 'Uganda',
    region: 'Africa',
    subRegion: 'Masaka',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.66',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Uganda Mbarara',
    country: 'Uganda',
    region: 'Africa',
    subRegion: 'Mbarara',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 10,
    price: '$15.63',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Uganda Okoro',
    country: 'Uganda',
    region: 'Africa',
    subRegion: 'Okoro',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$18.30',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Costa Rica Brunca',
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Brunca',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 8,
    price: '$15.58',
    flavorProfile: 'caramel & toffee',
  },
  {
    name: 'Costa Rica Orosi',
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Orosi',
    roastLevel: 'Medium-Dark',
    type: 'Blend',
    bagWeight: 12,
    price: '$22.11',
    flavorProfile: 'strong & smooth',
  },
  {
    name: 'Costa Rica Tarrazu',
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Tarrazu',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.85',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Costa Rica Tres Rios',
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Tres Rios',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 10,
    price: '$16.54',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Costa Rica Turrialba',
    country: 'Costa Rica',
    region: 'Central America',
    subRegion: 'Turrialba',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.97',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'El Salvador Apaneca',
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Apaneca',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.63',
    flavorProfile: 'sweet & smooth',
  },
  {
    name: 'El Salvador Cacahuatique',
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Cacahuatique',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.48',
    flavorProfile: 'balanced & fruity',
  },
  {
    name: 'El Salvador Chalatenango',
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Chalatenango',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.19',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'El Salvador Metapán',
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Metapán',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$12.32',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'El Salvador Santa Ana',
    country: 'El Salvador',
    region: 'Central America',
    subRegion: 'Santa Ana',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.96',
    flavorProfile: 'sweet & smooth',
  },
  {
    name: 'Guatemala Acatenango',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Acatenango',
    roastLevel: 'Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.77',
    flavorProfile: 'chocolate & cherry',
  },
  {
    name: 'Guatemala Antigua',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Antigua',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 8,
    price: '$15.16',
    flavorProfile: 'chocolate & cherry',
  },
  {
    name: 'Guatemala Atitlán',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Atitlán',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.91',
    flavorProfile: 'chocolate & cherry',
  },
  {
    name: 'Guatemala Cobán',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Cobán',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$15.74',
    flavorProfile: 'roasty & smoky',
  },
  {
    name: 'Guatemala FraiJanes',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'FraiJanes',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 12,
    price: '$16.12',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Guatemala Huehuetenango',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'Huehuetenango',
    roastLevel: 'Light-Medium',
    type: 'Blend',
    bagWeight: 12,
    price: '$22.81',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Guatemala New Oriente',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'New Oriente',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.77',
    flavorProfile: 'rich & comforting',
  },
  {
    name: 'Guatemala San Marcos',
    country: 'Guatemala',
    region: 'Central America',
    subRegion: 'San Marcos',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.36',
    flavorProfile: 'chocolate & cherry',
  },
  {
    name: 'Honduras Agalta',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Agalta',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.55',
    flavorProfile: 'balanced & fruity',
  },
  {
    name: 'Honduras Comayagua',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Comayagua',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.37',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Honduras Copán',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Copán',
    roastLevel: 'Medium',
    type: 'Blend',
    bagWeight: 12,
    price: '$22.10',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Honduras El Paraiso',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'El Paraiso',
    roastLevel: 'Medium',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$16.93',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Honduras Montecillos',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Montecillos',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.81',
    flavorProfile: 'honey & peach',
  },
  {
    name: 'Honduras Opalaca',
    country: 'Honduras',
    region: 'Central America',
    subRegion: 'Opalaca',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.90',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Mexico Chiapas',
    country: 'Mexico',
    region: 'Central America',
    subRegion: 'Chiapas',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$12.71',
    flavorProfile: 'roasty & smoky',
  },
  {
    name: 'Mexico Oaxaca',
    country: 'Mexico',
    region: 'Central America',
    subRegion: 'Oaxaca',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.73',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Mexico Veracruz',
    country: 'Mexico',
    region: 'Central America',
    subRegion: 'Veracruz',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.69',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Nicaragua Esteli',
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Esteli',
    roastLevel: 'Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.59',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Nicaragua Jinotega',
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Jinotega',
    roastLevel: 'Light',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$12.31',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Nicaragua Madriz',
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Madriz',
    roastLevel: 'Light',
    type: 'Blend',
    bagWeight: 10,
    price: '$15.21',
    flavorProfile: 'sweet & tart',
  },
  {
    name: 'Nicaragua Matagalpa',
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Matagalpa',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.34',
    flavorProfile: 'almond & vanilla',
  },
  {
    name: 'Nicaragua Nueva Segovia',
    country: 'Nicaragua',
    region: 'Central America',
    subRegion: 'Nueva Segovia',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.37',
    flavorProfile: 'rich & comforting',
  },
  {
    name: 'Brazil Atlantico Baiano',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Atlantico Baiano',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.67',
    flavorProfile: 'caramel & toffee',
  },
  {
    name: 'Brazil Centro-Oeste de São Paulo',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Centro-Oeste de São Paulo',
    roastLevel: 'Medium',
    type: 'Blend',
    bagWeight: 12,
    price: '$18.30',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Brazil Cerrado and Planalto da Bahia',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Cerrado and Planalto da Bahia',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.42',
    flavorProfile: 'roasty & smoky',
  },
  {
    name: 'Brazil Cerrado de Minas',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Cerrado de Minas',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$18.39',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Brazil Chapada de Minas',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Chapada de Minas',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$15.47',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Brazil Conilon Capixaba',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Conilon Capixaba',
    roastLevel: 'Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$22.76',
    flavorProfile: 'rich & comforting',
  },
  {
    name: 'Brazil Matas de Minas',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Matas de Minas',
    roastLevel: 'Medium',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$16.66',
    flavorProfile: 'caramel & toffee',
  },
  {
    name: 'Brazil Mogiana',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Mogiana',
    roastLevel: 'Medium',
    type: 'Blend',
    bagWeight: 12,
    price: '$16.80',
    flavorProfile: 'cocoa & brown sugar',
  },
  {
    name: 'Brazil Montanhas do Espírito Santo',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Montanhas do Espírito Santo',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.83',
    flavorProfile: 'maple & orange zest',
  },
  {
    name: 'Brazil Sul de Minas',
    country: 'Brazil',
    region: 'South America',
    subRegion: 'Sul de Minas',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 12,
    price: '$16.71',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Peru Amazonas',
    country: 'Peru',
    region: 'South America',
    subRegion: 'Amazonas',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$12.88',
    flavorProfile: 'sweet & smooth',
  },
  {
    name: 'Peru Chanchamayo',
    country: 'Peru',
    region: 'South America',
    subRegion: 'Chanchamayo',
    roastLevel: 'Medium-Dark',
    type: 'Single Origin',
    bagWeight: 10,
    price: '$15.95',
    flavorProfile: 'bold & heavy',
  },
  {
    name: 'Peru San Martin',
    country: 'Peru',
    region: 'South America',
    subRegion: 'San Martin',
    roastLevel: 'Light-Medium',
    type: 'Single Origin',
    bagWeight: 8,
    price: '$15.44',
    flavorProfile: 'cocoa & brown sugar',
  },
];

export const BasicStack = () => (
  <Flex border="solid 2px" flexDirection="row" alignItems="flex-start" flexWrap="wrap" padding="s">
    {data.map(coffee => (
      <Flex
        border="solid 1px"
        padding="xs"
        flexDirection="column"
        flexBasis="25%"
        flexGrow="0"
        flexShrink="1"
        margin="s"
        alignSelf="stretch"
      >
        <h4>{coffee.name}</h4>
        <p>{coffee.flavorProfile}</p>
      </Flex>
    ))}
  </Flex>
);
