import {ExternalHyperlink, TertiaryButton} from '@workday/canvas-kit-react/button';
import {Card} from '@workday/canvas-kit-react/card';
import {Tooltip} from '@workday/canvas-kit-react/tooltip';
import {createStyles} from '@workday/canvas-kit-styling';
import {infoSparkleIcon} from '@workday/canvas-system-icons-web';
import {system} from '@workday/canvas-tokens-web';

const containerStyles = createStyles({
  background: system.color.bg.alt.default,
  padding: system.padding.xl,
});

export const AIDisclosure = () => {
  return (
    <div className={containerStyles}>
      <Card>
        <Card.Heading>
          Giant Pacific Octopus
          <Tooltip title="This content is generated by AI" variant="alt" placement="right-end">
            <TertiaryButton
              size="extraSmall"
              icon={infoSparkleIcon}
              aria-label="This functionality is powered by AI"
            />
          </Tooltip>
        </Card.Heading>
        <Card.Body>
          The giant Pacific octopus (Enteroctopus dofleini), also known as the North Pacific giant
          octopus, is a large marine cephalopod belonging to the genus Enteroctopus and
          Enteroctopodidae family. –{' '}
          <ExternalHyperlink href="https://en.wikipedia.org/wiki/Giant_Pacific_octopus">
            View Source
          </ExternalHyperlink>
        </Card.Body>
      </Card>
    </div>
  );
};
