import colors from '@workday/canvas-colors-web';
import {CanvasTheme, ContentDirection} from './types';
import {breakpoints, up, down, between, only} from './breakpoints';
import {cs} from '@workday/canvas-kit-styling';

export const defaultCanvasTheme: CanvasTheme = {
  palette: {
    primary: {
      lightest: colors.blueberry100,
      light: colors.blueberry200,
      main: colors.blueberry400,
      dark: colors.blueberry500,
      darkest: colors.blueberry600,
      contrast: colors.frenchVanilla100,
    },
    alert: {
      lightest: colors.cantaloupe100,
      light: colors.cantaloupe300,
      main: colors.cantaloupe400,
      dark: colors.cantaloupe500,
      darkest: colors.cantaloupe600,
      contrast: colors.frenchVanilla100,
    },
    error: {
      lightest: colors.cinnamon100,
      light: colors.cinnamon200,
      main: colors.cinnamon500,
      dark: colors.cinnamon600,
      darkest: '#80160E',
      contrast: colors.frenchVanilla100,
    },
    success: {
      lightest: colors.greenApple100,
      light: colors.greenApple300,
      main: colors.greenApple600,
      dark: '',
      darkest: '',
      contrast: colors.frenchVanilla100,
    },
    neutral: {
      lightest: colors.soap200,
      light: colors.soap300,
      main: colors.soap600,
      dark: colors.licorice300,
      darkest: colors.licorice400,
      contrast: colors.frenchVanilla100,
    },
    common: {
      focusOutline: colors.blueberry400,
    },
  },
  breakpoints: {
    values: breakpoints,
    up,
    down,
    between,
    only,
  },
  direction: ContentDirection.LTR,
};

export const newTheme = {
  fontFamilies: {
    default: '--canvas-font-family-default',
    monospace: '--canvas-font-family-monospace',
  },
  fontSizes: {
    10: '--canvas-font-size-10',
    12: '--canvas-font-size-12',
    14: '--canvas-font-size-14',
    16: '--canvas-font-size-16',
    18: '--canvas-font-size-18',
    20: '--canvas-font-size-20',
    24: '--canvas-font-size-24',
    28: '--canvas-font-size-28',
    32: '--canvas-font-size-32',
    40: '--canvas-font-size-40',
    48: '--canvas-font-size-48',
    56: '--canvas-font-size-56',
  },
  fontWeights: {
    regular: '--canvas-font-weights-regular',
    medium: '--canvas-font-weights-medium',
    bold: '--canvas-font-weights-bold',
  },
  colors: {
    alert: {
      lightest: '--canvas-colors-alert-lightest',
      light: '--canvas-colors-alert-light',
      main: '--canvas-colors-alert-main',
      dark: '--canvas-colors-alert-dark',
      darkest: '--canvas-colors-alert-darkest',
      contrast: '--canvas-colors-alert-contrast',
    },
    error: {
      lightest: '--canvas-colors-error-lightest',
      light: '--canvas-colors-error-light',
      main: '--canvas-colors-error-main',
      dark: '--canvas-colors-error-dark',
      darkest: '--canvas-colors-error-darkest',
      contrast: '--canvas-colors-error-contrast',
    },
    success: {
      lightest: '--canvas-colors-success-lightest',
      light: '--canvas-colors-success-light',
      main: '--canvas-colors-success-main',
      dark: '--canvas-colors-success-dark',
      darkest: '--canvas-colors-success-darkest',
      contrast: '--canvas-colors-success-contrast',
    },
    neutral: {
      lightest: '--canvas-colors-neutral-lightest',
      light: '--canvas-colors-neutral-light',
      main: '--canvas-colors-neutral-main',
      dark: '--canvas-colors-neutral-dark',
      darkest: '--canvas-colors-neutral-darkest',
      contrast: '--canvas-colors-neutral-contrast',
    },
    primary: {
      lightest: '--canvas-colors-primary-lightest',
      light: '--canvas-colors-primary-light',
      main: '--canvas-colors-primary-main',
      dark: '--canvas-colors-primary-dark',
      darkest: '--canvas-colors-primary-darkest',
      contrast: '--canvas-colors-primary-contrast',
    },
    common: {
      focusOutline: '--canvas-colors-primary-main',
    },
  },
  borderRadius: {
    zero: '--canvas-border-radius-zero',
    small: '--canvas-border-radius-small',
    medium: '--canvas-border-radius-medium',
    large: '--canvas-border-radius-large',
    circle: '--canvas-border-radius-circle',
  },
} as const;

// temporary theme injection
cs({
  ':root': {
    '--canvas-color-base-cinnamon-100': '#ffefee',
    '--canvas-color-base-cinnamon-200': '#fcc9c5',
    '--canvas-color-base-cinnamon-300': '#ff867d',
    '--canvas-color-base-cinnamon-400': '#ff5347',
    '--canvas-color-base-cinnamon-500': '#de2e21',
    '--canvas-color-base-cinnamon-600': '#a31b12',
    '--canvas-color-base-peach-100': '#fff3f0',
    '--canvas-color-base-peach-200': '#ffc2b3',
    '--canvas-color-base-peach-300': '#ff957a',
    '--canvas-color-base-peach-400': '#ff643d',
    '--canvas-color-base-peach-500': '#de4721',
    '--canvas-color-base-peach-600': '#b53413',
    '--canvas-color-base-chili-mango-100': '#ffe6d9',
    '--canvas-color-base-chili-mango-200': '#ffc7ab',
    '--canvas-color-base-chili-mango-300': '#ff9b69',
    '--canvas-color-base-chili-mango-400': '#ff671b',
    '--canvas-color-base-chili-mango-500': '#e04b00',
    '--canvas-color-base-chili-mango-600': '#a33600',
    '--canvas-color-base-cantaloupe-100': '#ffeed9',
    '--canvas-color-base-cantaloupe-200': '#fcd49f',
    '--canvas-color-base-cantaloupe-300': '#ffbc63',
    '--canvas-color-base-cantaloupe-400': '#ffa126',
    '--canvas-color-base-cantaloupe-500': '#f38b00',
    '--canvas-color-base-cantaloupe-600': '#c06c00',
    '--canvas-color-base-sour-lemon-100': '#fff9e6',
    '--canvas-color-base-sour-lemon-200': '#ffecab',
    '--canvas-color-base-sour-lemon-300': '#ffda61',
    '--canvas-color-base-sour-lemon-400': '#ffc629',
    '--canvas-color-base-sour-lemon-500': '#ebb400',
    '--canvas-color-base-sour-lemon-600': '#bd9100',
    '--canvas-color-base-juicy-pear-100': '#f7fae6',
    '--canvas-color-base-juicy-pear-200': '#e2f391',
    '--canvas-color-base-juicy-pear-300': '#c4de40',
    '--canvas-color-base-juicy-pear-400': '#a8c224',
    '--canvas-color-base-juicy-pear-500': '#8ea618',
    '--canvas-color-base-juicy-pear-600': '#687818',
    '--canvas-color-base-kiwi-100': '#ecfcd7',
    '--canvas-color-base-kiwi-200': '#caf593',
    '--canvas-color-base-kiwi-300': '#a7e05c',
    '--canvas-color-base-kiwi-400': '#77bc1f',
    '--canvas-color-base-kiwi-500': '#609915',
    '--canvas-color-base-kiwi-600': '#537824',
    '--canvas-color-base-green-apple-100': '#ebfff0',
    '--canvas-color-base-green-apple-200': '#acf5be',
    '--canvas-color-base-green-apple-300': '#5fe380',
    '--canvas-color-base-green-apple-400': '#43c463',
    '--canvas-color-base-green-apple-500': '#319c4c',
    '--canvas-color-base-green-apple-600': '#217a37',
    '--canvas-color-base-watermelon-100': '#ebfdf8',
    '--canvas-color-base-watermelon-200': '#b7edde',
    '--canvas-color-base-watermelon-300': '#65ccaf',
    '--canvas-color-base-watermelon-400': '#12a67c',
    '--canvas-color-base-watermelon-500': '#0c7a5b',
    '--canvas-color-base-watermelon-600': '#00573e',
    '--canvas-color-base-jewel-100': '#ebfdff',
    '--canvas-color-base-jewel-200': '#acecf3',
    '--canvas-color-base-jewel-300': '#44c8d7',
    '--canvas-color-base-jewel-400': '#1ea4b3',
    '--canvas-color-base-jewel-500': '#1a818c',
    '--canvas-color-base-jewel-600': '#156973',
    '--canvas-color-base-toothpaste-100': '#d7f1fc',
    '--canvas-color-base-toothpaste-200': '#99e0ff',
    '--canvas-color-base-toothpaste-300': '#40b4e5',
    '--canvas-color-base-toothpaste-400': '#1894c9',
    '--canvas-color-base-toothpaste-500': '#0271a1',
    '--canvas-color-base-toothpaste-600': '#005b82',
    '--canvas-color-base-blueberry-100': '#d7eafc',
    '--canvas-color-base-blueberry-200': '#a6d2ff',
    '--canvas-color-base-blueberry-300': '#40a0ff',
    '--canvas-color-base-blueberry-400': '#0875e1',
    '--canvas-color-base-blueberry-500': '#005cb9',
    '--canvas-color-base-blueberry-600': '#004387',
    '--canvas-color-base-plum-100': '#e6f1ff',
    '--canvas-color-base-plum-200': '#a6cdff',
    '--canvas-color-base-plum-300': '#529bfa',
    '--canvas-color-base-plum-400': '#3881e1',
    '--canvas-color-base-plum-500': '#3166ab',
    '--canvas-color-base-plum-600': '#264a7a',
    '--canvas-color-base-berry-smoothie-100': '#e8edff',
    '--canvas-color-base-berry-smoothie-200': '#c2cfff',
    '--canvas-color-base-berry-smoothie-300': '#7891ff',
    '--canvas-color-base-berry-smoothie-400': '#5e77e6',
    '--canvas-color-base-berry-smoothie-500': '#4b5eb3',
    '--canvas-color-base-berry-smoothie-600': '#3b4987',
    '--canvas-color-base-blackberry-100': '#f0f0ff',
    '--canvas-color-base-blackberry-200': '#c3c2ff',
    '--canvas-color-base-blackberry-300': '#8483e6',
    '--canvas-color-base-blackberry-400': '#5c59e6',
    '--canvas-color-base-blackberry-500': '#413fcc',
    '--canvas-color-base-blackberry-600': '#2e2d91',
    '--canvas-color-base-island-punch-100': '#f5f0ff',
    '--canvas-color-base-island-punch-200': '#d2befa',
    '--canvas-color-base-island-punch-300': '#a88ae6',
    '--canvas-color-base-island-punch-400': '#8660d1',
    '--canvas-color-base-island-punch-500': '#6345a1',
    '--canvas-color-base-island-punch-600': '#503882',
    '--canvas-color-base-grape-soda-100': '#feebff',
    '--canvas-color-base-grape-soda-200': '#fac0ff',
    '--canvas-color-base-grape-soda-300': '#de8ae6',
    '--canvas-color-base-grape-soda-400': '#c860d1',
    '--canvas-color-base-grape-soda-500': '#97499e',
    '--canvas-color-base-grape-soda-600': '#7c3882',
    '--canvas-color-base-pomegranate-100': '#ffebf3',
    '--canvas-color-base-pomegranate-200': '#ffbdd6',
    '--canvas-color-base-pomegranate-300': '#ff5c9a',
    '--canvas-color-base-pomegranate-400': '#f31167',
    '--canvas-color-base-pomegranate-500': '#c70550',
    '--canvas-color-base-pomegranate-600': '#99003a',
    '--canvas-color-base-fruit-punch-100': '#ffeeee',
    '--canvas-color-base-fruit-punch-200': '#ffbdbd',
    '--canvas-color-base-fruit-punch-300': '#ff7e7e',
    '--canvas-color-base-fruit-punch-400': '#ff4c4c',
    '--canvas-color-base-fruit-punch-500': '#e12f2f',
    '--canvas-color-base-fruit-punch-600': '#b82828',
    '--canvas-color-base-root-beer-100': '#faf3f0',
    '--canvas-color-base-root-beer-200': '#ebd7cf',
    '--canvas-color-base-root-beer-300': '#dcbbad',
    '--canvas-color-base-root-beer-400': '#ba9a8c',
    '--canvas-color-base-root-beer-500': '#8c7266',
    '--canvas-color-base-root-beer-600': '#664d42',
    '--canvas-color-base-toasted-marshmallow-100': '#fdf6e6',
    '--canvas-color-base-toasted-marshmallow-200': '#ebd6a9',
    '--canvas-color-base-toasted-marshmallow-300': '#e6bf6c',
    '--canvas-color-base-toasted-marshmallow-400': '#cc9e3b',
    '--canvas-color-base-toasted-marshmallow-500': '#b37f10',
    '--canvas-color-base-toasted-marshmallow-600': '#8c6000',
    '--canvas-color-base-coconut-100': '#f0eeee',
    '--canvas-color-base-coconut-200': '#e3dfdf',
    '--canvas-color-base-coconut-300': '#d1cbcc',
    '--canvas-color-base-coconut-400': '#b3acac',
    '--canvas-color-base-coconut-500': '#9e9595',
    '--canvas-color-base-coconut-600': '#8f8687',
    '--canvas-color-base-cappuccino-100': '#7a7374',
    '--canvas-color-base-cappuccino-200': '#706869',
    '--canvas-color-base-cappuccino-300': '#5e5757',
    '--canvas-color-base-cappuccino-400': '#4a4242',
    '--canvas-color-base-cappuccino-500': '#352f2f',
    '--canvas-color-base-cappuccino-600': '#231f20',
    '--canvas-color-base-soap-100': '#f6f7f8',
    '--canvas-color-base-soap-200': '#f0f1f2',
    '--canvas-color-base-soap-300': '#e8ebed',
    '--canvas-color-base-soap-400': '#dfe2e6',
    '--canvas-color-base-soap-500': '#ced3d9',
    '--canvas-color-base-soap-600': '#b9c0c7',
    '--canvas-color-base-licorice-100': '#a1aab3',
    '--canvas-color-base-licorice-200': '#7b858f',
    '--canvas-color-base-licorice-300': '#5e6a75',
    '--canvas-color-base-licorice-400': '#4a5561',
    '--canvas-color-base-licorice-500': '#333d47',
    '--canvas-color-base-licorice-600': '#1f262e',
    '--canvas-color-base-french-vanilla-100': '#ffffff',
    '--canvas-color-base-french-vanilla-200': '#ebebeb',
    '--canvas-color-base-french-vanilla-300': '#d4d4d4',
    '--canvas-color-base-french-vanilla-400': '#bdbdbd',
    '--canvas-color-base-french-vanilla-500': '#a6a6a6',
    '--canvas-color-base-french-vanilla-600': '#8f8f8f',
    '--canvas-color-base-black-pepper-100': '#787878',
    '--canvas-color-base-black-pepper-200': '#616161',
    '--canvas-color-base-black-pepper-300': '#494949',
    '--canvas-color-base-black-pepper-400': '#333333',
    '--canvas-color-base-black-pepper-500': '#1e1e1e',
    '--canvas-color-base-black-pepper-600': '#000000',
    '--canvas-color-transparent': 'rgba(0,0,0,0)',

    '--canvas-font-family-default': '"Roboto", "Helvetica Neue", "Helvetica", Arial, sans-serif',
    '--canvas-font-family-monospace': '"Roboto Mono", "Courier New", Courier, monospace',
    '--canvas-font-size-10': '0.625rem',
    '--canvas-font-size-12': '0.75rem',
    '--canvas-font-size-14': '0.875rem',
    '--canvas-font-size-16': '1rem',
    '--canvas-font-size-18': '1.125rem',
    '--canvas-font-size-20': '1.25rem',
    '--canvas-font-size-24': '1.5rem',
    '--canvas-font-size-28': '1.75rem',
    '--canvas-font-size-32': '2rem',
    '--canvas-font-size-40': '2.5rem',
    '--canvas-font-size-48': '3rem',
    '--canvas-font-size-56': '3.5rem',
    '--canvas-font-weights-regular': '400',
    '--canvas-font-weights-medium': '500',
    '--canvas-font-weights-bold': '700',
    '--canvas-colors-body': 'var(--canvas-color-base-black-pepper-300)',
    '--canvas-colors-heading': 'var(--canvas-color-base-black-pepper-400)',
    '--canvas-colors-hint': 'var(--canvas-color-base-licorice-300)',
    '--canvas-colors-inverse': 'var(--canvas-color-base-french-vanilla-100)',
    '--canvas-colors-label': 'var(--canvas-color-base-black-pepper-100)',
    '--canvas-colors-link': 'var(--canvas-color-base-blueberry-400)',
    '--canvas-colors-selectHighlight': 'var(--canvas-color-base-blueberry-200)',
    '--canvas-colors-selectHighlightInverse': 'var(--canvas-color-base-french-vanilla-100)',

    //Border Radius
    '--canvas-border-radius-zero': '0',
    '--canvas-border-radius-small': '0.125rem',
    '--canvas-border-radius-medium': '0.25rem',
    '--canvas-border-radius-large': '0.5rem',
    '--canvas-border-radius-circle': '999px',

    '--canvas-colors-primary-lightest': 'var(--canvas-color-base-blueberry-100)',
    '--canvas-colors-primary-light': 'var(--canvas-color-base-blueberry-200)',
    '--canvas-colors-primary-main': 'var(--canvas-color-base-blueberry-400)',
    '--canvas-colors-primary-dark': 'var(--canvas-color-base-blueberry-500)',
    '--canvas-colors-primary-darkest': 'var(--canvas-color-base-blueberry-600)',
    '--canvas-colors-primary-contrast': 'var(--canvas-color-base-french-vanilla-100)',
    '--canvas-colors-alert-lightest': 'var(--canvas-color-base-cantaloupe-100)',
    '--canvas-colors-alert-light': 'var(--canvas-color-base-cantaloupe-300)',
    '--canvas-colors-alert-main': 'var(--canvas-color-base-cantaloupe-400)',
    '--canvas-colors-alert-dark': 'var(--canvas-color-base-cantaloupe-500)',
    '--canvas-colors-alert-darkest': 'var(--canvas-color-base-cantaloupe-600)',
    '--canvas-colors-alert-contrast': 'var(--canvas-color-base-french-vanilla-100)',
    '--canvas-colors-error-lightest': 'var(--canvas-color-base-cinnamon-100)',
    '--canvas-colors-error-light': 'var(--canvas-color-base-cinnamon-200)',
    '--canvas-colors-error-main': 'var(--canvas-color-base-cinnamon-500)',
    '--canvas-colors-error-dark': 'var(--canvas-color-base-cinnamon-600)',
    '--canvas-colors-error-darkest': '#80160E',
    '--canvas-colors-error-contrast': 'var(--canvas-color-base-french-vanilla-100)',
    '--canvas-colors-success-lightest': 'var(--canvas-color-base-green-apple-100)',
    '--canvas-colors-success-light': 'var(--canvas-color-base-green-apple-300)',
    '--canvas-colors-success-main': 'var(--canvas-color-base-green-apple-600)',
    '--canvas-colors-success-dark': '',
    '--canvas-colors-success-darkest': '',
    '--canvas-colors-success-contrast': 'var(--canvas-color-base-french-vanilla-100)',
    '--canvas-colors-neutral-lightest': 'var(--canvas-color-base-soap-200)',
    '--canvas-colors-neutral-light': 'var(--canvas-color-base-soap-300)',
    '--canvas-colors-neutral-main': 'var(--canvas-color-base-soap-600)',
    '--canvas-colors-neutral-dark': 'var(--canvas-color-base-licorice-300)',
    '--canvas-colors-neutral-darkest': 'var(--canvas-color-base-licorice-400)',
    '--canvas-colors-neutral-contrast': 'var(--canvas-color-base-french-vanilla-100)',
  },
});
