name: ChromaticQA Master Rebasing

on:
  push:
    branches:
      - master

jobs:
  visual_rebasing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Packages
      run: yarn install

    # auto-accept changes to master assuming they came from approved PRs.
    # https://docs.chromaticqa.com/setup_ci#maintain-a-clean-master-branch
    - uses: chromaui/action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        appCode: dlpro96xybh
        autoAcceptChanges: true

