name: Close Linked Issues

on:
  pull_request_target:
    types: [closed]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: Workday/canvas-kit-actions/close-related-issues@38458d8f53521968d38ad2b839fe442fe3046c6a # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
