name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Get Package Scopes
        id: scope-vars
        run: echo "::set-output name=scopes::$(node utils/get-package-names.js)"

      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@db6e259b93f286e3416eef27aaae88935d16cf2e # v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: ${{steps.scope-vars.outputs.scopes}}
          subjectPattern: ^[A-Z].+$

      - uses: Workday/canvas-kit-actions/verify-pull-request@38458d8f53521968d38ad2b839fe442fe3046c6a # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

