name: "Lint PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Package Scopes
        id: scope-vars
        run: echo "::set-output name=scopes::$(node utils/get-package-names.js)"

      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: ${{steps.scope-vars.outputs.scopes}}
          subjectPattern: ^[A-Z].+$

