name: Reviewer Lottery

on:
  pull_request_target:
    types: [labeled]

jobs:
  assign:
    if: github.event.label.name == 'ready for review'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: uesteibar/reviewer-lottery@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
