name: Reviewer Lottery

on:
  pull_request_target:
    types: [labeled]

jobs:
  assign:
    if: github.event.label.name == 'ready for review'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: uesteibar/reviewer-lottery@5531ef7fe55d814c8f8fbab12de4ff74d15b41ed # v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
